---
title: "pca_svm"
author: "Daniel Schmidle - dps2150"
date: "3/17/2020"
output: html_document
---


```{r}
load("../output/feature_train.RData")
load("../output/feature_test.RData")
library(caTools)
library(caret)
library(e1071)
```


```{r}
#PCA
start_time <-  Sys.time()

dat_train[,-6007] <- scale(dat_train[,-6007])
dat_test[,-6007] <- scale(dat_test[,-6007])
 
pca <- preProcess(x=dat_train[-6007],method="pca",thresh=0.99)
dat_train <- predict(pca,dat_train)
dat_test <- predict(pca,dat_test)

end_time <- Sys.time()
cat("The time for PCA: ", end_time-start_time, " mins" )

```


```{r}
#CV on SVM cost parameter 

c_vals <- 2^(seq(-12,-8,0.5))
lin_tune <- tune(svm,emotion_idx~.,data=dat_train,kernel="linear",ranges=list(cost=c_vals),scale=F)
summary(lin_tune)

```



```{r}
#SVM model
start_time <-  Sys.time()

c <- lin_tune$best.parameters$cost
pca_svm <- svm(emotion_idx~.,
               data= dat_train,
               type="C",
               kernel="linear",
               scale=F,
               cost=c)
summary(pca_svm)


#test accuracy
test_pred <- predict(pca_svm,dat_test[,-1])

cm <- table(dat_test[,1],test_pred)
cm
acc <- cat("The test accuracy is: ", mean(test_pred==dat_test[,1])*100, " %")
acc

end_time <- Sys.time()
cat("The time for training the model and testing: ", end_time-start_time, " seconds" )
```

```{r}
#train accuracy
train_pred <- predict(pca_svm,dat_train[,-1])
cm <- table(dat_train[,1],train_pred)
cm
acc <- cat("The train accuracy is: ", mean(train_pred==dat_train[,1])*100, " %")
```


```{r}
#save model
saveRDS(pca_svm, "../output/pca_svm_model.RDS")
```

